services:
  online-server:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    build:
      context: .
    image: ceyewan/crypto-custody-online-server:latest
    container_name: crypto-custody-online-server
    restart: unless-stopped

    env_file:
      - .env
    environment:
      BACKEND_BIND_ADDR: 0.0.0.0
      BACKEND_PORT: ${BACKEND_PORT:-22221}
      DATABASE_PATH: ${DATABASE_PATH:-/app/database/crypto-custody.db}

    ports:
      - "${BACKEND_HOST_PORT:-22221}:${BACKEND_PORT:-22221}"

    volumes:
      - ./database:/app/database
      - ./logs:/app/logs

    networks:
      - crypto-custody-online-net

networks:
  crypto-custody-online-net:
    name: crypto-custody-online-net
    driver: bridge
