version: '3.8'

services:
  app:
    # 替换为你的 Docker Hub 用户名和镜像名
    image: ceyewan/crypto-custody-online-server:latest
    container_name: crypto-custody-server
    restart: unless-stopped

    # 从 .env 文件加载环境变量
    env_file:
      - .env

    # 不再将端口映射到宿主机，容器仅通过内部网络访问
    # ports:
    #   - "8080:8080"

    # 挂载卷以实现数据持久化
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs

    # 以有限权限运行容器是一个好习惯
    # 该用户应与 Dockerfile 中指定的用户匹配
    user: nonroot:nonroot

    # 将服务连接到特定的内部网络
    networks:
      - crypto-custody-online-net

networks:
  crypto-custody-online-net:
    name: crypto-custody-online-net
    driver: bridge
    internal: true