// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPLCInfo() {
  return window['go']['main']['App']['GetCPLCInfo']();
}

export function PerformDeleteMessage() {
  return window['go']['main']['App']['PerformDeleteMessage']();
}

export function PerformKeyGeneration() {
  return window['go']['main']['App']['PerformKeyGeneration']();
}

export function PerformSignMessage(arg1) {
  return window['go']['main']['App']['PerformSignMessage'](arg1);
}
