// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPLCInfo():Promise<any>;

export function PerformDeleteMessage():Promise<void>;

export function PerformKeyGeneration():Promise<any>;

export function PerformSignMessage(arg1:string):Promise<any>;
