// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMessage() {
  return window['go']['main']['App']['DeleteMessage']();
}

export function GetCPLC() {
  return window['go']['main']['App']['GetCPLC']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function KeyGeneration() {
  return window['go']['main']['App']['KeyGeneration']();
}

export function SignMessage(arg1) {
  return window['go']['main']['App']['SignMessage'](arg1);
}
