# 应用程序配置文件
debug: true
port: "23451"
temp_dir: "./temp"
bin_dir: "./bin"
keygen_bin: "gg20_keygen"
signing_bin: "gg20_signing"
security_chip: true
# Applet AID, 16进制字符串
applet_aid: "A000000062CF0101"
manager_addr: "http://localhost:8000"

# 日志配置
log_dir: "./logs"
log_file: "web-se.log"
log_max_size: 10 # 单个日志文件最大大小(MB)
log_max_backups: 10 # 保留的旧日志文件数量
log_max_age: 30 # 日志文件保留天数
log_compress: true # 是否压缩旧日志
